import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import javax.swing.DefaultListModel;
import java.util.Calendar;
import java.util.Date;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author NOEL
 */

public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    private final String ruta=System.getProperties().getProperty("user.dir");
    public Formulario() {
        initComponents();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now();  
        fechahora.setText(dtf.format(now));
        File doc=null;
        FileReader FileR= null;
        BufferedReader BufferedR=null;
        try{
            doc=new File(ruta+"//documento.txt");
            FileR=new FileReader(doc);
            BufferedR=new BufferedReader(FileR);
            String informacion;
            DefaultListModel lista=new DefaultListModel();
            //lista.addElement("Mostrar datos de archivo");
            while((informacion=BufferedR.readLine())!=null){
        System.out.println(informacion);
        lista.addElement(informacion);
        }
            listadatos.setModel(lista);
        }catch(Exception e){}finally{try{if(null!=FileR){FileR.close();}}catch(IOException e2){}{
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrupomm = new javax.swing.ButtonGroup();
        puntodeventa = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        iraproductos = new javax.swing.JButton();
        irmateriaprima = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        punto_venta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadatos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        descdeprod = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        preciovalor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        precioiva = new javax.swing.JTextField();
        rbmenoreo = new javax.swing.JRadioButton();
        rbmayoreo = new javax.swing.JRadioButton();
        materia_prima = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fechahora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        puntodeventa.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("¿Quienes Somos?");

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(240, 240, 240));
        jTextPane1.setText("Misión e impacto social.\n\nNuestra empresa busca ofrecer una opción más sustentable y amigable con el ambiente. \nOfrecemos cuero fabricado a base de piña para sustituir la piel animal que, además de contaminar, \npone en peligro de extinción a muchos animales.\n\t\t\t\t\t\t\t\t\t\nUtilizamos las coronas de las piñas para fabricar materia prima que posteriormente procesamos\npara generar productos, y así evitar la caza innecesaria de animales, reduciendo un poco la \ncontaminación orgánica. Además, nuestro porductos están elaborados artesanalmente, \nson de buena calidad y promueven la protección de los animales :)\t\t\t\t\t\t\t\t\t");
        jTextPane1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTextPane1);

        iraproductos.setText("Comprar Productos");
        iraproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iraproductosActionPerformed(evt);
            }
        });

        irmateriaprima.setText("Comprar Materia Prima");
        irmateriaprima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irmateriaprimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(iraproductos)
                        .addGap(18, 18, 18)
                        .addComponent(irmateriaprima))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irmateriaprima)
                    .addComponent(iraproductos))
                .addGap(27, 27, 27))
        );

        puntodeventa.addTab("Nosotros", jPanel1);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Punto de Venta");

        jScrollPane2.setViewportView(listadatos);

        jButton1.setText("Seleccionar este producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        descdeprod.setVisible(false);
        descdeprod.setEditable(false);
        descdeprod.setBackground(new java.awt.Color(240, 240, 240));
        descdeprod.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(descdeprod);

        jLabel5.setText("Precio unitario:");

        preciovalor.setEditable(false);
        preciovalor.setRequestFocusEnabled(false);
        preciovalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciovalorActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio unitario+iVA");

        precioiva.setEditable(false);
        precioiva.setRequestFocusEnabled(false);

        bgrupomm.add(rbmenoreo);
        rbmenoreo.setText("Compraré en Menoreo");
        rbmenoreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmenoreoActionPerformed(evt);
            }
        });

        bgrupomm.add(rbmayoreo);
        rbmayoreo.setText("Compraré en Mayoreo");

        javax.swing.GroupLayout punto_ventaLayout = new javax.swing.GroupLayout(punto_venta);
        punto_venta.setLayout(punto_ventaLayout);
        punto_ventaLayout.setHorizontalGroup(
            punto_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(punto_ventaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(punto_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(punto_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(punto_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(punto_ventaLayout.createSequentialGroup()
                        .addGroup(punto_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(punto_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preciovalor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioiva, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(punto_ventaLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addGroup(punto_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbmayoreo)
                    .addComponent(rbmenoreo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        punto_ventaLayout.setVerticalGroup(
            punto_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(punto_ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(punto_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(punto_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5)
                    .addComponent(preciovalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(punto_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(precioiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbmenoreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbmayoreo)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        puntodeventa.addTab("Punto de Venta", punto_venta);

        javax.swing.GroupLayout materia_primaLayout = new javax.swing.GroupLayout(materia_prima);
        materia_prima.setLayout(materia_primaLayout);
        materia_primaLayout.setHorizontalGroup(
            materia_primaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        materia_primaLayout.setVerticalGroup(
            materia_primaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        puntodeventa.addTab("Materia Prima", materia_prima);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/LOGO.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puntodeventa)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fechahora, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechahora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(puntodeventa, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iraproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iraproductosActionPerformed
punto_venta = new javax.swing.JPanel();
puntodeventa.setSelectedIndex(1);
    }//GEN-LAST:event_iraproductosActionPerformed

    private void irmateriaprimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irmateriaprimaActionPerformed
punto_venta = new javax.swing.JPanel();
puntodeventa.setSelectedIndex(2);
    }//GEN-LAST:event_irmateriaprimaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int elegido=listadatos.getSelectedIndex();
        
        
        bgrupomm.add(rbmenoreo);
        bgrupomm.add(rbmayoreo);
        if(elegido==0){
        descdeprod.setVisible(true);
        descdeprod.setText("Cierre de Abrazadera\n" +
        "Correa reversible de repuesto, viene con dos colores adicionales.\n" +
        "Correa de agujeros con el material propuesto por Fiñax.\n" +
        "Depende del tamaño, pero el estándar es reversible de 30 mm de ancho.\n" +
        "Bordes cosidos para mayor durabilidad.\n" +
        "El cinturón tiene la capacidad de medirse por medio del pliegue de la hebilla.");
        double precionormal=0;
        double preciomasiva=0;
        preciovalor.setText("$"+precionormal);
        precioiva.setText("$"+preciomasiva);
        }
        if(elegido==1){
        descdeprod.setVisible(true);
        descdeprod.setText("Cierre de sin cierre\n" +
            "Estructura: \n" +
            "   8 ranuras para tarjetas. \n" +
            "   Ventana de identificación. \n" +
            "   Compartimentos para dinero.\n" +
            "Tamaño aproximado: 11,4 x 8,9 x 1,7 cm.\n" +
            "Multiusos.");
        double precionormal=0;
        double preciomasiva=0;
        preciovalor.setText("$"+precionormal);
        precioiva.setText("$"+preciomasiva);
        }
        if(elegido==2){
        descdeprod.setVisible(true);
        descdeprod.setText("Cierre de Cremallera\n" +
        "2 bolsillos laterales con cremallera y decoración.\n" +
        "Cambiando el uso de piel, por producto Fiñax correa de hombro reforzada.\n" +
        "1 compartimento medio, 1 bolsillo con cremallera y 2 bolsillos con ranura, 1 bolsillo trasero con cremallera.");
        double precionormal=0;
        double preciomasiva=0;
        preciovalor.setText("$"+precionormal);
        precioiva.setText("$"+preciomasiva);
        }
        if(elegido==3){
        descdeprod.setVisible(true);
        descdeprod.setText("Los guantes están hechos de producto Fiñax en contraste a sus competidores, suaves y cómodos de llevar. \n" +
        "Cuentan con tecnología nano conductora que permite que puedas usar tus aparatos electrónicos táctiles sin necesidad de quitarte los elegantes guantes.\n" +
        "El diseño simple y clásico, es imprescindible durante el frío invierno, tanto en interiores como en exteriores.");
        double precionormal=0;
        double preciomasiva=0;
        preciovalor.setText("$"+precionormal);
        precioiva.setText("$"+preciomasiva);
        }
        if(elegido==4){
        descdeprod.setVisible(true);
        descdeprod.setText("Recordemos que no está hecha a base de piel, o cuero, si no está hecha de Fiñax.\n" +
        "Cremallera\n" +
        "Cómodo y flocado en su interior.\n" +
        "Características generales, puede pedir por personalizaciones: cintura alta, cierre de cremallera en la espalda, color sólido.\n" +
        "Se recomienda tener cuidado al lavar.");
        double precionormal=0;
        double preciomasiva=0;
        preciovalor.setText("$"+precionormal);
        precioiva.setText("$"+preciomasiva);
        }
        if(elegido==5){
        descdeprod.setVisible(true);
        descdeprod.setText("El zapato puede variar, pero el tamaño general es 100 mm o 120 mm.\n" +
        "Cuenta con suela antiderrapante para evitar accidentes. \n" +
        "Puede pedir un diseño personalizado.");
        double precionormal=0;
        double preciomasiva=0;
        preciovalor.setText("$"+precionormal);
        precioiva.setText("$"+preciomasiva);
        }
        if(elegido==6){
        descdeprod.setVisible(true);
        descdeprod.setText("De nuevo cambiamos el uso de piel o cuero.\n" +
        "6 paneles en la parte superior de Fiñax.\n" +
        "Por dentro tiene una capa de algodón, este forro de algodón y el cinturón absorbente de sudor mantienen la cabeza seca y transpirable.\n" +
        "No se lava a máquina y tener sumo cuidado al hacerlo.");
        double precionormal=0;
        double preciomasiva=0;
        preciovalor.setText("$"+precionormal);
        precioiva.setText("$"+preciomasiva);
        }
        if(elegido==7){
        descdeprod.setVisible(true);
        descdeprod.setText("Se pide, al igual que con los otros productos, lavar con cuidado a mano.\n" +
        "Están hechos de Fiñax, de nuevo siendo un sustituto del cuero y piel, tela segura de alta calidad que ofrece una excelente experiencia de uso, suave, agradable al tacto y cómodo.\n" +
        "Puede variar dependiendo de la personalización que el cliente guste darle, pero en general: Color sólido, cintura elástica, cintura alta, pierna recta.");
        double precionormal=0;
        double preciomasiva=0;
        preciovalor.setText("$"+precionormal);
        precioiva.setText("$"+preciomasiva);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void preciovalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciovalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preciovalorActionPerformed

    private void rbmenoreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmenoreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmenoreoActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrupomm;
    private javax.swing.JTextPane descdeprod;
    private javax.swing.JLabel fechahora;
    private javax.swing.JButton iraproductos;
    private javax.swing.JButton irmateriaprima;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JList<String> listadatos;
    private javax.swing.JPanel materia_prima;
    private javax.swing.JTextField precioiva;
    private javax.swing.JTextField preciovalor;
    private javax.swing.JPanel punto_venta;
    public javax.swing.JTabbedPane puntodeventa;
    private javax.swing.JRadioButton rbmayoreo;
    private javax.swing.JRadioButton rbmenoreo;
    // End of variables declaration//GEN-END:variables
}
